version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: 
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: evadock/foodgram_backend:latest
    restart: always
    env_file:
      - ../.env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: evadock/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  nginx:
    image: evadock/foodgram_infra:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
      - frontend
    env_file:
      - ../.env
