version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: 
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: evadock/foodgram_backend:latest
    restart: always
    env_file:
      - ../.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: evadock/foodgram_frontend:latest
    env_file: 
      - ../.env
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: evadock/foodgram_infra:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend
    env_file:
      - ../.env
