name: Main Foodgram Workflow

on:
  push:
    branches:
      - main

env: 
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Print project tree
        run: tree .

  